# Standard library imports
import json
import logging
import argparse
from pathlib import Path

# Third party imports
import torch
from tqdm import tqdm

# Local imports (assuming your combined class is in serializers.py)
from .serializers import HumdrumSerializer, MinimalHumdrumSerializer

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def process_single_graph(graph_path: Path, json_dir: Path, out_dir: Path, node_roles: dict) -> bool:
    """Loads a graph and its associated JSONs, calculates centers, and exports **kern."""
    try:
        # 1. Load the PyG graph dictionary
        graph_data = torch.load(graph_path, weights_only=False)
        edge_index = graph_data["edge_index"]
        edge_predictions = graph_data["y"]  # Using Ground Truth labels for this generation
        valid_node_ids = set(graph_data["node_ids"])
        
        # 2. Load and merge the associated JSON annotation files
        raw_nodes = []
        for json_filename in graph_data.get("json_files", []):
            json_path = json_dir / json_filename
            if not json_path.exists():
                logger.warning(f"Missing JSON annotation: {json_filename}")
                continue
                
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                raw_nodes.extend(data.get("annotations", []))
                
        if not raw_nodes:
            return False

        # 3. Filter nodes present in the graph and calculate spatial centers (cx, cy)
        node_map = {}
        for ann in raw_nodes:
            if "id" in ann:
                base_id = ann["id"]
                if base_id in node_map:
                    # Recreate the exact pseudo-ID generated by the graph builder
                    pseudo_id = f"{base_id}_{ann['class']}_{len(node_map)}"
                    ann["id"] = pseudo_id
                    node_map[pseudo_id] = ann
                else:
                    node_map[base_id] = ann
        processed_nodes = []
        for node in node_map.values():
            node_id = node.get("id")
            if node_id in valid_node_ids:
                x1, y1, x2, y2 = node["bbox"]
                
                # Enrich the dictionary with center coordinates required by the serializer
                node["cx"] = (x1 + x2) / 2.0
                node["cy"] = (y1 + y2) / 2.0
                processed_nodes.append(node)

        # 4. Initialize the Serializer and generate the stream
        serializer = MinimalHumdrumSerializer(
            node_list=processed_nodes,
            edge_index=edge_index,
            edge_predictions=edge_predictions,
            node_roles=node_roles,
            pyg_node_ids=graph_data["node_ids"] # <-- ADD THIS LINE
        )
        
        kern_stream = serializer.export_to_krn()
        
        # 5. Save the output
        out_file = out_dir / f"{graph_path.stem}.krn"
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(kern_stream)
            f.write("\n") # Ensure trailing newline
            
        return True

    except Exception as e:
        logger.error(f"Failed to process {graph_path.name}: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="Generate Humdrum **kern from PyG graphs and JSONs.")
    parser.add_argument("--graph_dir", type=str, default="data/output_graphs", help="Dir with .pt files")
    parser.add_argument("--json_dir", type=str, default="data/annotations", help="Dir with .json files")
    parser.add_argument("--out_dir", type=str, default="data/output_kern", help="Output directory for .krn")
    parser.add_argument("--roles_file", type=str, default="conf/structure.json", help="Path to node roles")
    args = parser.parse_args()

    graph_dir = Path(args.graph_dir)
    json_dir = Path(args.json_dir)
    out_dir = Path(args.out_dir)
    roles_path = Path(args.roles_file)

    if not graph_dir.exists():
        logger.error(f"Graph directory not found: {graph_dir}")
        return
        
    if not roles_path.exists():
        logger.error(f"Roles file not found: {roles_path}")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    
    with open(roles_path, "r", encoding="utf-8") as f:
        node_roles = json.load(f)

    graph_files = list(graph_dir.glob("*.pt"))
    logger.info(f"Found {len(graph_files)} graphs to process.")

    success_count = 0
    with tqdm(total=len(graph_files), desc="Exporting **kern") as pbar:
        for g_path in graph_files:
            if process_single_graph(g_path, json_dir, out_dir, node_roles):
                success_count += 1
            pbar.update(1)

    logger.info(f"Finished. Successfully generated {success_count}/{len(graph_files)} Humdrum files.")

if __name__ == "__main__":
    main()