# Standard library imports
import json
import logging
import argparse
from pathlib import Path

# Third party imports
import torch
from tqdm import tqdm

# Local imports (assuming your combined class is in serializers.py)
from .serializers import MinimalHumdrumSerializer

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def _load_and_resolve_nodes(json_dir: Path, json_filenames: list) -> tuple[dict, list[set]]:
    """Load JSON annotation files in order, resolving pseudo-ID collisions.

    Returns:
        node_map: dict mapping resolved node IDs to their annotation dicts.
        page_node_ids: list of sets, one per JSON file, tracking which IDs belong to each page.
    """
    node_map = {}
    page_node_ids = []

    for json_filename in json_filenames:
        json_path = json_dir / json_filename
        if not json_path.exists():
            logger.warning(f"Missing JSON annotation: {json_filename}")
            page_node_ids.append(set())
            continue

        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        page_ids = set()
        for ann in data.get("annotations", []):
            if "id" not in ann:
                continue

            base_id = ann["id"]
            if base_id in node_map:
                # Recreate the exact pseudo-ID generated by the graph builder
                pseudo_id = f"{base_id}_{ann['class']}_{len(node_map)}"
                ann["id"] = pseudo_id
                node_map[pseudo_id] = ann
                page_ids.add(pseudo_id)
            else:
                node_map[base_id] = ann
                page_ids.add(base_id)

        page_node_ids.append(page_ids)

    return node_map, page_node_ids


def _build_page_nodes(node_map: dict, page_ids: set, valid_node_ids: set) -> list:
    """Filter a page's nodes to those present in the graph and enrich with center coordinates."""
    processed = []
    for node_id in page_ids:
        if node_id not in valid_node_ids:
            continue

        node = node_map[node_id]
        x1, y1, x2, y2 = node["bbox"]
        node["cx"] = (x1 + x2) / 2.0
        node["cy"] = (y1 + y2) / 2.0
        processed.append(node)

    return processed


def process_single_graph(graph_path: Path, json_dir: Path, out_dir: Path, node_roles: dict) -> bool:
    """Loads a graph and its associated JSONs, calculates centers, and exports **kern."""
    try:
        # 1. Load the PyG graph dictionary
        graph_data = torch.load(graph_path, weights_only=False)
        edge_index = graph_data["edge_index"]
        edge_predictions = graph_data["y"]
        valid_node_ids = set(graph_data["node_ids"])

        # 2. Load all JSON files and resolve pseudo-IDs (must match graph builder order)
        json_filenames = graph_data.get("json_files", [])
        node_map, page_node_ids = _load_and_resolve_nodes(json_dir, json_filenames)

        if not node_map:
            return False

        # 3. Initialize serializer once and feed pages one at a time
        serializer = MinimalHumdrumSerializer(
            edge_index=edge_index,
            edge_predictions=edge_predictions,
            node_roles=node_roles,
            pyg_node_ids=graph_data["node_ids"],
        )

        for page_ids in page_node_ids:
            page_nodes = _build_page_nodes(node_map, page_ids, valid_node_ids)
            if page_nodes:
                serializer.add_page(page_nodes)

        # 4. Export and save
        kern_stream = serializer.export_to_krn()
        if kern_stream.startswith("Error"):
            logger.warning(f"{graph_path.name}: {kern_stream}")
            return False

        out_file = out_dir / f"{graph_path.stem}.krn"
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(kern_stream)
            f.write("\n")

        return True

    except Exception as e:
        logger.error(f"Failed to process {graph_path.name}: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="Generate Humdrum **kern from PyG graphs and JSONs.")
    parser.add_argument("--graph_dir", type=str, default="data/output_graphs", help="Dir with .pt files")
    parser.add_argument("--json_dir", type=str, default="data/annotations", help="Dir with .json files")
    parser.add_argument("--out_dir", type=str, default="data/output_kern", help="Output directory for .krn")
    parser.add_argument("--roles_file", type=str, default="conf/structure.json", help="Path to node roles")
    args = parser.parse_args()

    graph_dir = Path(args.graph_dir)
    json_dir = Path(args.json_dir)
    out_dir = Path(args.out_dir)
    roles_path = Path(args.roles_file)

    if not graph_dir.exists():
        logger.error(f"Graph directory not found: {graph_dir}")
        return
        
    if not roles_path.exists():
        logger.error(f"Roles file not found: {roles_path}")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    
    with open(roles_path, "r", encoding="utf-8") as f:
        node_roles = json.load(f)

    graph_files = list(graph_dir.glob("*.pt"))
    logger.info(f"Found {len(graph_files)} graphs to process.")

    success_count = 0
    with tqdm(total=len(graph_files), desc="Exporting **kern") as pbar:
        for g_path in graph_files:
            if process_single_graph(g_path, json_dir, out_dir, node_roles):
                success_count += 1
            pbar.update(1)

    logger.info(f"Finished. Successfully generated {success_count}/{len(graph_files)} Humdrum files.")

if __name__ == "__main__":
    main()